#ifndef TODOSTORAGE_TEST_H
#define TODOSTORAGE_TEST_H

void runTodoStorageTests();
void createTodosFromJSONString_WithNullStr_ReturnZeroTodo();
void createTodosFromJSONString_WithEmptyStr_ReturnZeroTodo();
void createTodosFromJSONString_WithWhiteSpacesStr_ReturnZeroTodo();
void createTodosFromJSONString_WithNotArrayStr_ReturnZeroTodo();
void createTodosFromJSONString_WithEmptyArrayStr_ReturnZeroTodo();
void createTodosFromJSONString_WithOneTodoOnlyNameStr_ReturnOneTodo();
void createTodosFromJSONString_WithTwoTodosOnlyNameStr_ReturnTwoTodos();

void createJSONStringFromTodos_WithNullList_ReturnEmptyJSONArray();
void createJSONStringFromTodos_WithListOneTodoOnlyName_ReturnJSONArrayOneItem();
void createJSONStringFromTodos_WithListTwoTodosOnlyName_ReturnJSONArrayTwoItems();
#endif